<#
.SYNOPSIS
    TopiVra production key generator
.DESCRIPTION
    Generates all required security keys and writes them to server/.env
    SMTP, payment and OAuth settings can be configured in the admin panel after deployment.
.EXAMPLE
    .\gen-keys.ps1
    .\gen-keys.ps1 -Force
    .\gen-keys.ps1 -Force -Domain example.com
#>

param(
    [switch]$Force = $false,
    [string]$Domain = ""
)

$envFile = Join-Path $PSScriptRoot "server\.env"

if ((Test-Path $envFile) -and -not $Force) {
    Write-Host "[INFO] server/.env already exists. Use -Force to overwrite." -ForegroundColor Yellow
    exit 0
}

function New-RandomString {
    param([int]$Length = 64)
    $chars = (48..57) + (65..90) + (97..122)
    return -join ($chars | Get-Random -Count $Length | ForEach-Object { [char]$_ })
}

# Ask for domain if not provided
if (-not $Domain) {
    Write-Host ""
    Write-Host "================================================" -ForegroundColor Cyan
    Write-Host "  TopiVra Key Generator v2.0" -ForegroundColor Cyan
    Write-Host "================================================" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Enter your domain or server IP" -ForegroundColor Yellow
    Write-Host "  Examples: example.com  /  1.2.3.4" -ForegroundColor Gray
    Write-Host "  Press Enter to use 'localhost' (local testing only)" -ForegroundColor Gray
    Write-Host ""
    $Domain = Read-Host "Domain"
    if (-not $Domain) { $Domain = "localhost" }
}

$useHttps = ($Domain -ne "localhost") -and ($Domain -notmatch '^\d+\.\d+\.\d+\.\d+$')
$baseUrl  = if ($useHttps) { "https://$Domain" } else { "http://$Domain" }
$apiUrl   = if ($useHttps) { "https://$Domain" } else { "http://$Domain:3001" }
$cbUrl    = "$apiUrl/api/v1/auth/google/callback"

Write-Host ""
Write-Host "================================================" -ForegroundColor Cyan
Write-Host "  TopiVra Key Generator v2.0" -ForegroundColor Cyan
Write-Host "  Domain : $baseUrl" -ForegroundColor Cyan
Write-Host "================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Generating secure keys..." -ForegroundColor Cyan

$MYSQL_ROOT_PASSWORD = New-RandomString -Length 40
$MYSQL_PASSWORD      = New-RandomString -Length 40
$REDIS_PASSWORD      = New-RandomString -Length 40
$JWT_SECRET          = New-RandomString -Length 64
$JWT_REFRESH_SECRET  = New-RandomString -Length 64
$ENCRYPTION_KEY      = New-RandomString -Length 32
$USDT_CB_SECRET      = New-RandomString -Length 32

$timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'

$lines = @(
    "# ============================================================"
    "# TopiVra Production Environment Config"
    "# Generated by gen-keys.ps1 at $timestamp"
    "# Domain: $baseUrl"
    "# WARNING: Do NOT commit this file to version control!"
    "# ============================================================"
    ""
    "# ==================== App ===================="
    "NODE_ENV=production"
    "PORT=3001"
    "APP_PORT=3001"
    "API_VERSION=v1"
    "API_PREFIX=api/v1"
    ""
    "# ==================== Database ===================="
    "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD"
    "MYSQL_DATABASE=topivra_prod"
    "MYSQL_USER=topivra_user"
    "MYSQL_PASSWORD=$MYSQL_PASSWORD"
    "DATABASE_URL=mysql://topivra_user:$MYSQL_PASSWORD@mysql:3306/topivra_prod"
    ""
    "# ==================== Redis ===================="
    "REDIS_PASSWORD=$REDIS_PASSWORD"
    "REDIS_HOST=redis"
    "REDIS_PORT=6379"
    "REDIS_URL=redis://:$REDIS_PASSWORD@redis:6379"
    ""
    "# ==================== JWT Security ===================="
    "JWT_SECRET=$JWT_SECRET"
    "JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET"
    "ENCRYPTION_KEY=$ENCRYPTION_KEY"
    ""
    "# ==================== Frontend URL ===================="
    "CLIENT_URL=$baseUrl"
    "FRONTEND_URL=$baseUrl"
    ""
    "# ==================== Google OAuth Callback ===================="
    "# clientId / clientSecret can be set in Admin Panel -> System Config -> OAuth"
    "GOOGLE_CALLBACK_URL=$cbUrl"
    ""
    "# ==================== SMTP ===================="
    "# All SMTP settings can be configured in Admin Panel -> System Config -> SMTP"
    "SMTP_HOST="
    "SMTP_PORT=587"
    "SMTP_USER="
    "SMTP_PASS="
    "SMTP_FROM=noreply@$Domain"
    ""
    "# ==================== Payment ===================="
    "# All payment settings can be configured in Admin Panel -> System Config -> Payment"
    "USDT_CALLBACK_SECRET=$USDT_CB_SECRET"
    ""
    "# ==================== Monitoring (optional) ===================="
    "SENTRY_DSN="
    "ENABLE_SWAGGER=false"
)

$envContent = $lines -join "`n"

# Ensure directory exists
$serverDir = Join-Path $PSScriptRoot "server"
if (-not (Test-Path $serverDir)) {
    New-Item -ItemType Directory -Path $serverDir | Out-Null
}

# Write UTF-8 without BOM
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($envFile, $envContent, $utf8NoBom)

Write-Host ""
Write-Host "[OK] Keys generated successfully!" -ForegroundColor Green
Write-Host "     Written to: server\.env" -ForegroundColor White
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Run DEPLOY-PROD.bat to start production environment" -ForegroundColor Gray
Write-Host "  2. Open $baseUrl/admin and login" -ForegroundColor Gray
Write-Host "  3. Go to System Config to set SMTP / Payment / OAuth" -ForegroundColor Gray
Write-Host ""
Write-Host "[WARNING] Never commit server\.env to Git!" -ForegroundColor Red
Write-Host ""

